DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS bookings;


CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(200) NOT NULL,
    owner_id BIGINT NOT NULL,
    count_rents INT NOT NULL DEFAULT 0,
    available BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_item_owner FOREIGN KEY(owner_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    who_booked BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    start_rent TIMESTAMP NOT NULL,
    end_rent TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT('WAITING'),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_booker_id FOREIGN KEY(who_booked) REFERENCES users(id),
    CONSTRAINT fk_item_id FOREIGN KEY(item_id) REFERENCES items(id),
    CONSTRAINT chk_future_rent CHECK (start_rent > CURRENT_TIMESTAMP),
    CONSTRAINT chk_rent_period CHECK (end_rent > start_rent)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(1000) NOT NULL,
    item_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY(item_id) REFERENCES items(id),
    FOREIGN KEY(author_id) REFERENCES users(id)
);

CREATE INDEX idx_bookings_user ON bookings(who_booked);
CREATE INDEX idx_bookings_item ON bookings(item_id);
CREATE INDEX idx_bookings_period ON bookings(start_rent, end_rent);

CREATE INDEX idx_comments_user ON comments(author_id);
CREATE INDEX idx_comments_item ON comments(item_id);